### ISSUE TITLE
Clarify saving in new location?

### ISSUE THREAD

**Issue by clare45** [AguaClara/mathcad#5]
Heyo @juanchon998 

is there a reason you said to keep a version updated in a new location rather than making a branch with all the correct and updated design aspects (such as the correct Filter Trunk and Branch Diameters with the correct everything else from 7055?)

Wondering because I've only looked at the files from the master branch so far, but if versioning is gonna be a weird thing having a branch that comes from earlier version and then lives in parallel might be easier?

Presumably I'll be working with it decently often if I'm seeing where updates might be able to go along with transferring to RST. 

thoughts?

**Comment by juanchon998** [comment]
Heyo,

So I suggested that because I'm playing around a lot with a lot of aspects of the code and many different files. I like to check out the newest files on the most recent version of the design tool while I am also working with the files from 7055. If I'm doing all that in the same github repo, I need to checkout a different branch. That means committing my changes. The more changes I commit, the more I bury Drew's actual version of 7055 and not my messy ones:

![image](https://user-images.githubusercontent.com/27255695/46031887-5c9ad800-c0b7-11e8-8a2d-cec7199ff9d7.png)

Additionally, I like to have the 7055 version of EStaRS and the newest version of EStaRS up at once, and that can only be done when I copy over one of them to a new location on my computer. The complicating factor is that each file uses different versions of MathFunctions, PipeDatabase, ExpertInputs, MaterialsDatabase, and FluidsFunctions because everything evolves messily. So they need their own, separate, different references. Thus I think it's just much neater to have a completely separate folder in my computer for version 7055 (or any other one).

If you can find a way around that which works for you then please use it!

**Comment by clare45** [comment]
This makes sense now and is much simpler than it seemed!

**Comment by fletchapin** [comment]
It seems you guys resolved this but when I saw it earlier Juan's comment:

> If I'm doing all that in the same github repo, I need to checkout a different branch. That means committing my changes.

Made me think that `git stash` could be useful in situations like this. If you're not familiar with it [here's the documentation](https://git-scm.com/docs/git-stash). If `git stash` is useless carry on with what you're doing because it seems like it's working.

**Comment by juanchon998** [comment]
> If `git stash` is useless

😆 So I've never been able to use git stash correctly, that's the kicker. If I were to learn it I'm sure it would be useful, but even so I think I like having two separate locations for all of these files for mathcad referencing.
